name       : gnuplot
version    : 5.4.9
release    : 21
source     :
    - https://download.sourceforge.net/project/gnuplot/gnuplot/5.4.9/gnuplot-5.4.9.tar.gz : a328a021f53dc05459be6066020e9a71e8eab6255d3381e22696120d465c6a97
license    : gnuplot
component  : programming
summary    : Gnuplot is a portable command-line driven graphing utility
description: |
    Gnuplot is a portable command-line driven graphing utility
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(pangocairo)
    - pkgconfig(x11)
    - wxwidgets-devel
setup      : |
    %configure --with-readline=gnu --with-qt=no
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/%libdir%
