name       : gnuplot
version    : 5.4.6
release    : 17
source     :
    - https://download.sourceforge.net/project/gnuplot/gnuplot/5.4.6/gnuplot-5.4.6.tar.gz : 02fc27918200ed64d8f0c3b84fe81b95b59cd47ad99f270939ae497c19f27419
license    : gnuplot
component  : programming
summary    : Gnuplot is a portable command-line driven graphing utility
description: |
    Gnuplot is a portable command-line driven graphing utility
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(pangocairo)
    - pkgconfig(x11)
    - wxwidgets-devel
setup      : |
    %configure --with-readline=gnu
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/%libdir%
