name       : gnuplot
version    : 5.2.7
release    : 11
source     :
    - https://sourceforge.net/projects/gnuplot/files/gnuplot/5.2.7/gnuplot-5.2.7.tar.gz/download : 97fe503ff3b2e356fe2ae32203fc7fd2cf9cef1f46b60fe46dc501a228b9f4ed
license    : gnuplot
component  : programming
summary    : Gnuplot is a portable command-line driven graphing utility
description: |
    Gnuplot is a portable command-line driven graphing utility
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(pangocairo)
    - pkgconfig(x11)
    - wxwidgets-devel
setup      : |
    %configure --with-readline=gnu
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/%libdir%
