name       : gnuplot
version    : 5.0.4
release    : 2
source     :
    - http://ufpr.dl.sourceforge.net/project/gnuplot/gnuplot/5.0.4/gnuplot-5.0.4.tar.gz : 151cb845728bde75eb9d1561b35140114a05a7c52a52bd35b4b2b3d944e0c31e
license    : GPL-2.0
component  : programming
summary    : Gnuplot is a portable command-line driven graphing utility
description: |
    Gnuplot is a portable command-line driven graphing utility
builddeps  :
    - pkgconfig(x11)
    - wxwidgets-devel
setup      : |
    %configure --prefix=/usr --with-readline=gnu
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/%libdir%
