name       : gnuplot
version    : 5.4.3
release    : 14
source     :
    - https://sourceforge.net/projects/gnuplot/files/gnuplot/5.4.3/gnuplot-5.4.3.tar.gz/download : 51f89bbab90f96d3543f95235368d188eb1e26eda296912256abcd3535bd4d84
license    : gnuplot
component  : programming
summary    : Gnuplot is a portable command-line driven graphing utility
description: |
    Gnuplot is a portable command-line driven graphing utility
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(pangocairo)
    - pkgconfig(x11)
    - wxwidgets-devel
setup      : |
    %configure --with-readline=gnu
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/%libdir%
