name       : gnuplot
version    : 5.0.3
release    : 3
source     :
    - http://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.3/gnuplot-5.0.3.tar.gz : 5f6ee35f3f22014058e999911934bfa9db28e02a2722a7001c192cd182b8c715
license    : GPL-2.0
component  : programming
summary    : Gnuplot is a portable command-line driven graphing utility
description: |
    Gnuplot is a portable command-line driven graphing utility
builddeps  :
    - readline-devel
    - wxwidgets-devel
setup      : |
    %configure --prefix=/usr --with-readline=gnu
build      : |
    %make
install    : |
    %make_install
